### ISSUE TITLE
Insertion causes memory corruption

### ISSUE THREAD

**Issue by VergilUa** [marijnz/NativeOctree#4]
I've ran a bunch of tests with different random bound setups, as well as different entity numbers, as a result -> ran into memory corruption issue:

This line https://github.com/marijnz/NativeOctree/blob/master/Assets/NativeOctree.cs#L161
`UnsafeUtility.WriteArrayElement(elements->Ptr, node.firstChildIndex + node.count, incomingElements[i]);`

Causes
`NullReferenceException: Object reference not set to an instance of an object
System.Buffer.memcpy4 (System.Byte* dest, System.Byte* src, System.Int32 size) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Buffer.Memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.String.memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Unity.Collections.LowLevel.Unsafe.UnsafeUtility.WriteArrayElement[T] (System.Void* destination, System.Int32 index, T value) (at <42a5878ce129403083acccf18e43363f>:0)`

This can be only seen when running Unity with -debugallocator command argument. 
Without it - this causes a hard crash upon UnsafeList Destroy call -> Free / memory deallocation.

(Tree properties - 6 depth, 16 maxLeafElements, 1000 inserting elements, and random bounds - uniform, but not int rounded)

I do not fully understand the algorithm, so if have any suggestions how to fix it - that would be great. Thanks.

**Comment by marijnz** [comment]
Hey, thanks for opening the issue.

I just had a quick fresh look and don't see anything very obvious with. Would have to debug it. Hopefully got some time in the coming days.

As for a suggestion: The issue is most likely a discrepency between the amount of elements expected on a node and the actual amount being added. The code in "Prepare the tree leaf nodes" needs to match that of "Add elements to leaf nodes".
The algorithm can be pretty hard to understand, so I understand if that doesn't help you much..

**Comment by VergilUa** [comment]
Managed to simplify WTR / dump positions + bounds:
1. Make sure you're running Unity with "Unity.exe -debugallocator -projectPath *pathToProject*";
2. Run MemCpyBugTest from here:
https://gist.github.com/VergilUa/12962a444fe106a0b815dfbf359fee58

At least this should help in reproducing it faster;

Also, I've already tried making bounds / center / extents int ceiled - no luck, same issue.

**Comment by VergilUa** [comment]
Think I found whats wrong, its DepthSizeLookup that has invalid sizes (has `2*2` instead of `2*2*2` per index);
Took a peek at NativeQuadTree lookups, and realized this;

Not sure if its the actual cause, but test passes successfully with this table:
https://gist.github.com/VergilUa/25132271980f57b0b46e31e0e112798f

Instead of:
https://gist.github.com/VergilUa/47be54e9084e111aae73deb79781e720

Need to run some more tests to be certain though.

**Comment by marijnz** [comment]
Wow. Good find. That's very likely the culprit then. At least an important fix.

**Comment by VergilUa** [comment]
After a couple of hours of stress testing, and extensive playmode entry / exits without debug allocator - can confirm that this is indeed the cause of hard crashes;

Feel free to close this issue once lookup table is fixed in the repo.

**Comment by marijnz** [comment]
Great, you could make a PR and link this issue?

**Comment by VergilUa** [comment]
Done, probably worth adding test as well, but unfortunately it relies on Entities package. So idk.
